### ISSUE TITLE
gendb errors on package biicode

### ISSUE THREAD

**Issue by bemeurer** [Jguer/yay#100]
When running `yay --gendb` it errors when installing [biicode](https://aur.archlinux.org/packages/biicode)
```
==> Installing biicode
Error installing biicode : invalid variable:
pkgbase
```

**Comment by Morganamilo** [comment]
Alright should be fixed here mikkeloscar/gopkgbuild#6. Might take awhile for this to get into yay/master though.

**Comment by Jguer** [comment]
I'll try and update the vendored packages as soon as possible to implement
the fix

**Comment by Morganamilo** [comment]
Here is probably not the place but do you have any plans to removing the vendors from the repo? maybe use git sub-modules instead or pull them using go get.

**Comment by Morganamilo** [comment]
The fix has been merged upstream now.

**Comment by maximbaz** [comment]
Regarding removing vendors from the repo, I have a very pleasant experience using [golang/dep](https://github.com/golang/dep) in another project of mine, definitely recommend.

**Comment by Morganamilo** [comment]
Personally I don't think we need anything more than git and a makefile. Any thing else is overly complected for 3 deps.

**Comment by Jguer** [comment]
I have been using golang/dep but I do believe Morgana is right. As long as
the source packages in the aur get built consistently overcomplicating
should be avoided

On Jan 17, 2018 03:43, "Morgana" <notifications@github.com> wrote:

Personally I don't think we need anything more than git and a makefile. Any
thing else is overly complected for 3 deps.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Jguer/yay/issues/100#issuecomment-358063635>, or mute
the thread
