### ISSUE TITLE
RFC: Change completion operation to -Pc. Add new options around P

### ISSUE THREAD

**Issue by Jguer** [Jguer/yay#104]
Following #75 and the new argument parser I propose changing `yay --complete` to `yay -Pc`.

`-P` stands for print
`-Pc` stands for print completion and it should use `$SHELL` to check if it should print the more detailed fish completions

(Useful for people with custom WM configurations and widgets)
`-Pn` should print the number of updates (#75)
`-Pu` should print the name of packages for update (#75)

Maybe `-Y --stats` can also be changed to `-Ps` (print statistics)?

**Comment by Morganamilo** [comment]
I already changed some of this a while ago, you may have merged without reading it fully.
I Added -Y/--yay that refers to yay specific options, -Y is also the default if no other operation is set.
I also renamed -Qstats to --stats so its now called like so.

```
yay --stats
yay --Y --stats
yay --yay --stats
```

I thought it was a good idea to dump the Yay actions into its own namespace.

Just wanted to give a quick reminder because you still mentioned -Qstats.

I agree with your plan though. -Y/--yay is for misc stuff that has no better place. If we had a punch of print related actions -P would be a good place to hold them.

**Comment by Jguer** [comment]
Sorry, I mentioned -Qstats out of habit, that's how it's named in my brain.
Since -G is also a new op outside of pacman, I believe -P should be good for printing.

print config can also be ported there (-Pd print defaults?)

**Comment by Morganamilo** [comment]
Sounds good, for good practice though I like having a long options for every short option
```
-n --numberupgrades
-u --upgrades
-d --defaultconfig
```
Those look fine?

**Comment by Jguer** [comment]
That looks nice indeed, any idea for the default action of -P?

**Comment by Morganamilo** [comment]
Didn't even think of that, either nop or error is all I can think of now.

**Comment by Morganamilo** [comment]
For debug reasons I would probably find it useful if yay could print the JSON values from some of the aur queries. Specifically Info and Search.

**Comment by Jguer** [comment]
yay -Pji (print json info)
yay -Pjs (print json search)

and as a bonus once a proper human friendly config print is done:
yay -Pjc (print json of config)
