### ISSUE TITLE
Handle AUR votes

### ISSUE THREAD

**Issue by renom** [Jguer/yay#1075]
Please add support for managing AUR votes likewise `yaourt` does that using `aurvote`. That's behavior is to ask whether package is needed to be voted or not, but once at all (so it isn't annoying like if it kept asking after each package update).

**Comment by Zebradil** [comment]
Another option is to ask once but on the first update rather than on the initial install. Or even implement «Yes/No/Ask later» options.
I often use yay for searching available packages (like `yay gopro`) and trying them out. So, before I install a package I do not always know if I'd like to vote for it.

**Comment by ghost** [comment]
That's the only thing i've been missing so far in yay @Zebradil @Jguer @renom.

Possible to integrate aurvote in the near future ?

**Comment by Jguer** [comment]
https://github.com/Jguer/yay/pull/1765 implements simple un/vote in yay

- Requires `AUR_USERNAME` and `AUR_PASSWORD` to be set
- `yay -Wv <packages>` votes for packages
- `yay -Wu <packages>` removes votes from packages

--

I'd be interested in adding:

- [ ] Option to list voted for packages
- [ ] Prompts to add vote on install/upgrade
- [ ] Prompts to remove vote on uninstall 

feedback on option naming/docs/env variable naming is most welcome
