### ISSUE TITLE
support for marking a package as devel?

### ISSUE THREAD

**Issue by nicman23** [Jguer/yay#1105]
So i have published some packages (ie [dxvk-winelib](https://aur.archlinux.org/packages/dxvk-winelib/)) with the following mindset:

get the git history, 
in pkgver: check the latest tag and checkout it

it is a git package but because it only builds tags it is probably not useful to mark it as such but it ought to be a devel package (because ppl mark it as obsolete).

maybe a flag in the pkgbuild to mark it as such?

**Comment by Morganamilo** [comment]
I'm not quite sure the AUR encourages that approach. I expect the more correct way to do it is normal pkgver bumping like every one else.

But aside from that, what makes you think yay does not treat it as a devel package?

**Comment by nicman23** [comment]
should it ? it does not show on a `yay -Syu --devel`

**Comment by Morganamilo** [comment]
It should show up if there are new commits. Looking at the repo there seems to be a constant stream, so it probably should have popped up for you.

What's your vcs.json look like?

**Comment by nicman23** [comment]
hmm you are correct, it now shows up. sorry for the invalid issue

**Comment by Morganamilo** [comment]
> I'm not quite sure the AUR encourages that approach. I expect the more correct way to do it is normal pkgver bumping like every one else.

Turns out it's not just discouraged but explicitly allowed. You should change your pkgbuild to be more *normal* otherwise it's gonna end up being deleted.

**Comment by eli-schwartz** [comment]
Among other issues, this actually runs git checkout during pkgver(), then redirects the output in order to work around makepkg attempting to capture the output as the value of `pkgver=`

This violates makepkg separation of steps, and means that pkgver(), which always runs after prepare(), will actually revert changes done by the former.

For a package as broken and rules-breaking as this, I cannot fathom why one would wish to add yay-specific special sauce in order to make --devel show updates to something that isn't a "development" version of a package....

**Comment by nicman23** [comment]
i really do not care if it is deleted to be honest. it is for my use and if someone else also wanted to use it that is also cool.

also just because it breaks runs does not mean it is not useful.

> For a package as broken and rules-breaking as this, I cannot fathom why one would wish to add yay-specific special sauce in order to make --devel show updates to something that isn't a "development" version of a package....

because people flagged it out of date and that is annoying
