### ISSUE TITLE
Feature request: Move built packages in pacman's cache directory

### ISSUE THREAD

**Issue by cmonty14** [Jguer/yay#1118]
#### Affected Version

yay v9.4.2 - libalpm v12.0.1

#### Feature request
Move built packages in pacman's cache directory

This function is provided by other helpers, e.g. trizen.
Hereby it's simpler to reuse builds with other installations instead of building on each installation individually.

**Comment by Jguer** [comment]
I'm mobile but I think this has been answered before with using /etc/makepkg.conf's PKGDEST

**Comment by 74cmonty** [comment]
OK.
I have entered this parameter in _/etc/makepkg.conf_:
`PKGDEST=/var/cache/pacman/pkg`

This is the default location for all packages.

However, after executing yay I get this error message:
```
==> FEHLER: You do not have write permission for the directory $PKGDEST (/var/cache/pacman/pkg).
    Breche ab...
```

This makes sense because I don't run yay as user _root_.

This means this solution won't work like other helpers.

**Comment by Morganamilo** [comment]
The error is pretty self evident. You don't have permission for that dir. I wouldn't mixing repo and AUR packages anayway. Choose a different dir.
