### ISSUE TITLE
Separate git repos from project directories?

### ISSUE THREAD

**Issue by mxmilkiib** [Jguer/yay#1138]
For a large project, e.g. Linux and Kodi, there is not just one package available. This takes up time, download bandwidth and local storage space.

Maybe separating the git repo directory from the package directory (and symlinking) might be worth it?

**Comment by Jguer** [comment]
If I get your proposal straight you want to split the `pkg/` directory from this repository into smaller git repositories.

- yay is not as large as linux or kodi, not by a long shot
- everything in pkg is consumed by yay since there's no stable API.
- cloning a series of small repos is generally slower than a medium sized repo (data needed)
