### ISSUE TITLE
License compliancy inacuracy in PKGBUILD

### ISSUE THREAD

**Issue by iTanguy** [Jguer/yay#1170]
#### Affected Version
`yay v9.4.4 - libalpm v12.0.1`

#### Issue

I'm not a lawyer, but licensing information in ArchLinux package is not fully compliant.

I know that PKGBUILD file is not hosted here, but I got directed here when leaving a comment on [AUR](https://aur.archlinux.org/packages/yay/).

#### Steps to reproduce
1. Look at license of sources in upstream repository (here on GitHub)
2. Check Archlinux packaging guidelines
3. Install yay
4. Check package license declaration
5. Check custom license files present in package

#### Output

1. Projects is mostly GPLv3, but among the included thrid-party copies in the repository, one of them (go-alpm) is apparently licensed under MIT

2. According [Archlinux packaging guidelines](https://wiki.archlinux.org/index.php/PKGBUILD#license)  `GPL3` should be used projects under `GPL3`; `GPL` should be use for _GPLv2 or any later version_

4. package is declared as "GPL"
> $ yay -Qi yay | grep Licenses
> Licenses        : GPL
> $

AFAIK, it should be declared as `GPL3 MIT` in PKGBUILD file.

5. No custom license file in the Archlinux package
> $ yay -Ql yay | grep licenses
> $

AFAIK, the MIT license file for go-alpm should be installed so that copyright be quoted as required.

**Comment by Morganamilo** [comment]
About the MIT thing. I once asked Eli about it and he insisted It should just be GPL. (GPL in the generic sense, you may be right about the GPL-3 thing)

**Comment by iTanguy** [comment]
Forgive my ignorance, but I have no clue who `Eli` might be.

Anyway, what is announced as being license under MIT is in `yay/vendor/github.com/Jguer/go-alpm`. I say this based on the LICENSE file and the header comments of .c and .go files. License is what it says and should be applied.

If Eli is the author of this code ans is willing to change the license to GPL, it's probably much _easier_ ! But I think he'll need to do himself, for example in its upstream repository. It may be illegal to just commit new LICENSE file and header comments yourself. Alternatively, the project may be put under double license GPL + MIT.

**Comment by Morganamilo** [comment]
Eli is a trusted user and packages some stuff in community.

Also it's perfectly fine to re-licence MIT code to GPL seems as GPL meets all of MIT's terms.

**Comment by eli-schwartz** [comment]
https://wiki.archlinux.org/index.php/PKGBUILD#license

"GPL" is correct for what SPDX might refer to as  GPL-2.0-or-later, "GPL3" is correct for  GPL-3.0-only or  GPL-3.0-or-later.

GPL is a famously viral license, and in order to use it, any MIT licensed code it links to ends up being effectively distributed under the terms of the GPL too -- you can relicense MIT to GPL, and incorporating it in a larger GPL code is, practically speaking, this. cf. "combined works"

Since this project statically links the MIT-licensed code into GPL code, there's no practical distinction for it being MIT, it would matter more if go-alpm were a shared library that could be separately linked to by additional projects (which might wish to depend on yay, but only link directly to go-alpm). In this case, it would be of value to convey go-alpm under the MIT license rather than "upgrading" it to GPL, because third-party consumers might wish to use it in projects that are compatible with the MIT, but not the GPL.

**Comment by eli-schwartz** [comment]
> AFAIK, the MIT license file for go-alpm should be installed so that copyright be quoted as required.

Although this is true even if you relicense it under the GPL, you still need to mention the copyright line. That's not exposed in pacman's license field, though, just in the installed license in /usr/share/licenses/$pkgname/

**Comment by Jguer** [comment]
Can't find the issue for it but I'm pretty sure this topic has been floated before.

If anything I think I'll change the PKGBUILD license to `GPL3` to be more precise but from my understanding due to the "viral" nature of GPL and the fact that the bindings to the alpm library are not shared with any other package in the system, makes the **distribution** of yay effectively GPL3 as argued by eli.

**Comment by iTanguy** [comment]
> Alternatively, the project may be put under double license GPL + MIT.

Sorry if I caused confusion when I wrote this. I was speaking only for the go-alpm sub-project, the whole yay project should remain GPL3 of course.

> Some projects have a manifest of files with the various licenses they contain, which might be useful here I guess? Basically an enhanced LICENSE file.

From my understanding, such a need is somehow adressed by SPDX and Debian's [DEP-5](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/).

> you can relicense MIT to GPL

Not exactly, from my understanding. There is no _difficulty_ of using MIT code from GPL code, and the result "combined work" can be distributed by respecting the requirements of *both* licenses. GPL puts more requirements on source code availability (and on "virality"), but MIT requirement on "copyright quote" must still be followed.

So practically, this derived work should be under "GPL and MIT" constraints.There is similar use case  in Debian DEP-5 [syntax examples § 7.2](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#license-syntax)

>  This is for a file that has both GPL and classic BSD code in it:
>
> License: GPL-2+ and BSD-3-clause

However, I am not sure how the Licenses field in PKGBUILD is meant to be filled. It can't be as expressive and accurate as SPDX or Debian copyright files... Maybe adding SPDX support to Archlinux was considered by someone ? I doubt so.

But my feeling is that the Licenses field is meant for users to identify license and copyright constrains. For example, if someone would want to distribute (free of charge or not) a product derived from Archlinux, the Licenses field should help identify the copyright and license constraints. If it's not accurate, it may be useless.

**Comment by iTanguy** [comment]
Reviving the ticket... So my understanding is :
- MIT copyright file from libalpm.so should be copied into `/usr/share/licenses/yay/`
- `License` field in` PKGBUILD` should be modified from `GPL` to `GPL3`
- but no need to add `MIT` to the `License` field of `PKGBUILD` file

Too bad I can't make a Pull Request, as the file is not hosted here.

**Comment by Jguer** [comment]
> Reviving the ticket... So my understanding is :
> 
>     * MIT copyright file from libalpm.so should be copied into `/usr/share/licenses/yay/`
> 
>     * `License` field in` PKGBUILD` should be modified from `GPL` to `GPL3`
> 
>     * but no need to add `MIT` to the `License` field of `PKGBUILD` file
> 
> 
> Too bad I can't make a Pull Request, as the file is not hosted here.

@iTanguy you can make a PR on https://github.com/Jguer/yay-PKGBUILD if you wish to add this
