### ISSUE TITLE
Install as many packages as possible

### ISSUE THREAD

**Issue by dnut** [Jguer/yay#1247]
If a single build fails, the entire application crashes. yay should assume that AUR packages are flaky and be able to robustly handle their failures without crashing.

If I am upgrading a total of 30 packages, and there are 5 separate packages that each cause an error during build, then I need to run yay at least 6 times before I can upgrade all the other packages that are perfectly fine. I run yay, see a failure, figure out which package failed, then run yay again, telling it to ignore that package this time. This is a frustrating cycle of trial and error that sometimes takes days to complete. 

I can deal with broken packages some other time, it's not that big of a deal that a few AUR packages fail to build. It is a big deal that I can't keep my system relatively up to date because yay fails to upgrade anything 90% of the time.

yay should prioritize getting good packages up to date rather than failing the entire process just because of one troublesome package. 

If any step of a build fails, yay should:
1. Log an error.
2. Skip installing any packages that depend on the failed package.
3. Continue to build and install the remaining packages.
4. Summarize failures indicating which ones were skipped and the cause.

**Comment by HaleTom** [comment]
Related:

* Suggestion: have a way to continue interrupted AUR installs/builds. #1199
* ignore errors and continue to build more packages #848

**Comment by HaleTom** [comment]
I have sufficient packages that generally one will have some problem, which means that ALL don't get updated unless I manually intervene and ignore the failing package(s).

Are the any work-arounds for this?  Eg, is there a way of getting `yay` to print just the AUR package names that it would update so that a `bash` could loop over them all?

**Comment by HaleTom** [comment]
First run:

    pac -Sauw --answerupgrade=None --answerclean=None

This will show you all the diffs. Say No when asked to install.

Then run:

    for pkg in $(yay -aQuq); do yay -Sa --answerclean=None --answerdiff=None "$pkg"; done

This will not show any diffs for packages that have been updated since the first command runs.

I consider this to be a security hole, so I'd love to see another workaround or ideally a fix such as `--continue`.

**Comment by grandchild** [comment]
@HaleTom 
> Are the any work-arounds for this? Eg, is there a way of getting `yay` to print just the AUR package names that it would update so that a `bash` could loop over them all?

How about
```shell
yay -Qua
```
or (probably more useful for your context):
```shell
yay -Qqua
```
?

**Comment by grandchild** [comment]
I think this issue should be closed in favor of #848
