### ISSUE TITLE
Yay does not update rc(release candidate) packages

### ISSUE THREAD

**Issue by Dialga** [Jguer/yay#1268]
#### Affected Version

yay v9.4.7 - libalpm v12.0.1
#### Steps to reproduce

1. yay

#### Output
Problem: aur package deno-bin version 1.0.0_rc3-1 is installed in my system, I ran `yay` to update my aur packages. deno-bin version 1.0.0-1 is released in the aur, but yay did not see that as an update.
Running `yay deno` shows 1.0.0_rc3-1 is installed despite 1.0.0-1 available.

Expected outcome: yay to update the release candidate package to version 1.0.0-1.

What happened: Yay did not update my deno-bin package despite version 1 being released, not a rc version.

**Comment by aswild** [comment]
This is an issue with the package's version (and how it's interpreted/compared by pacman) rather than anything to do with yay.

`vercmp 1.0.0_rc1 1.0.0` prints `1`, which means it treats 1.0.0_rc1 as a newer version than 1.0.0. If I remove the underscore, `vercmp 1.0.0rc1 1.0.0` prints `-1` which is the expected order. Ask the package maintainer to fix the version numbering in the PKGBUILD.

See the [vercmp(8)](https://www.archlinux.org/pacman/vercmp.8.html) manpage for details.
