### ISSUE TITLE
Feature Request: Automatic rebuilds on dependency updates

### ISSUE THREAD

**Issue by RubenKelevra** [Jguer/yay#1269]
I maintain a package with a program which is written in go.

On every go-update I have either to push a new pkgrel version, or every user have to manually trigger a rebuild.

It would be great if yay could analyse the system updates made since the last build an trigger rebuilts itself.

**Comment by stertingen** [comment]
This is also interesting for ROS users: https://github.com/ros-noetic-arch/ros-noetic-desktop-full/issues/10. There is https://github.com/maximbaz/rebuild-detector/ which may be useful in some cases, especially since it does some sort of system analysis.

A feature similar to the `--rebuildtree` flag could be to recursively rebuild packages that depend (directly or transitively) on an updated package; these packages might be rebuild in their dependency order.

For example, if `boost` is updated, I'd like to type:
`yay --rebuild-dependants-of boost` to update all packages depending directly on boost, then all packages depending on the packages depending directly on boost and so on.

**Comment by AchmadFathoni** [comment]
Do you find any solution?

**Comment by RubenKelevra** [comment]
@stertingen I feel like this should be fully automated - not with any manual intervention. If there's for example a security fix in Golang for a build-in library, I would currently have to push an empty update to a package build with Golang, just to trigger a rebuild on all user's systems.

Else the security issue would never been patched if there's not a new release for the software I maintain.

Since this is a possible security vulnerability of Yay itself (basically) I think this should get priority.

Yay should keep track of the versions of build dependencies used to build the package. If a version in this list has changed either previously (via running pacman) or is planned to be changed on an update, Yay should put the package for a forced rebuild and a forced reinstall on the update list on the next update.

@Jguer can you please reopen this ticket, it's not fixed or invalid, just haven't got any attention.

**Comment by grandchild** [comment]
But many many packages are perfectly fine with a dependency update without the rebuild. For example I don't want every `mingw-*` package to be rebuilt just because some fundamental library changes.

So the proper way to do this would be to either:
1. mark dependencies as rebuild-triggers, or
2. push a new pkgbuild version

Archlinux official packages currently do 2, for example Haskell packages. So I also pushed new pkgbuilds for all my AUR python packages when Python 3.9 came out.

Solution 1 would be a new AUR feature so you'd have to take it up with the AUR or even pacman projects.

**Comment by RubenKelevra** [comment]
@grandchild if you want to skip certain packages from rebuilding maybe a feature like the "packages to clean build" list, where you can select certain ones as a user.

All selected will be removed from the list of packages needed to be rebuild, for this update.

Or do you think about having a blocklist somewhere of packages that don't need a rebuild at all?

Would it be save to skip all mingw-* packages if the makedepend has been updated? If so, why?

**Comment by grandchild** [comment]
I get the impression you think it's the norm that packages have to be updated/rebuilt because the (make-)depends get updated. It's not.

Rather it's a special case of software written in languages like Haskell (that doesn't have a stable ABI, so symbols move around on recompile) and Go (which links libraries in statically instead of dynamically).

So what I'm suggesting is that if you want such a list it would have to be the inverse. I.e. packages that _need_ a rebuild after depends updates. Because most packages don't.

**Comment by grandchild** [comment]
More detail: each dependency on each package would need a flag whether it will trigger a rebuild (with a default of "false" imo). For example a Go package might have both an actual library dependency and a tool that generates the manpage. An update to the first might trigger a rebuild, while an update to the manpage tool will not, because the output would still be the same manpage.

**Comment by grandchild** [comment]
Personally I feel that updating the package (even with just a pkgrel change) is what the package maintainer has to do. That's part of the job description, and it's what the official packages currently do. (Even to _extremes_: just install `pandoc`, and leave it on your system for a few weeks. You'll see...)

I'd be all in favour if the arch packaging system could detect this automatically in some way, but that's not something that yay can fix on its own.
