### ISSUE TITLE
Option for verbose output

### ISSUE THREAD

**Issue by Raymo111** [Jguer/yay#1320]
Can we get a --verbose option to show what yay is doing?

**Comment by grandchild** [comment]
Hm, sorry to be on your case again ;), but:

1. Your problem was sorted out with good old strace, no? So I'm wondering what the new usecase of this flag would be _exactly_?
1. `pacman` already has a `--verbose` flag which does something slightly different.
1. yay (and pacman for that matter) does print out a lot of what it's doing.

It could be argued that such a "more" verbose option would be of some use for debugging, but might not be something the general user would need?

Just a few thoughts, maybe contributors want to weigh in?

**Comment by Raymo111** [comment]
Hehe you have a good point ;)

However, I'm so used to almost every Linux program having a --verbose flag that I'm surprised yay doesn't already. It'd be nice to get one, and yes, it won't be used by users normally, but then again no one uses the --verbose flag on other programs normally either :P

**Comment by grandchild** [comment]
@Jguer this needs your input, if you'd be willing to have such a flag (what would its name be? `--verbose` already exists.), or not (my personal preference, I don't see much value atm, except for in-depth debugging).

Either way, this issue should be either closed or labeled as "enhancement".

**Comment by Jguer** [comment]
I would actually use `--verbose` as well for yay since we also extend a series of other pacman flags, I just don't know what would be the most useful to verbose print:

This is a small list I can think off:
- Print pacman command to execute
- Pretty print dependency pool and dependency graph 
- Print devel packages checked for updates

**Comment by Raymo111** [comment]
I'm good with that, if that's all that isn't being displayed right not. It could also call the pacman `--verbose` option?

**Comment by SheMelody** [comment]
I'm having trouble installing python-libmamba with yay and I need a more verbose output of what yay is doing, because the output just says "subcommand failed, error 4" and I can't understand what that means. Is there a chance we can implement this or do I have to install this package manually instead of relying on yay?
