### ISSUE TITLE
How can we seach file name in any AUR package through entire AUR 

### ISSUE THREAD

**Issue by abdulbadii** [Jguer/yay#1337]
How can we seach file name in any AUR package throughout entire AUR database,
is it possible now or the feature will be created ?

**Comment by grandchild** [comment]
Since AUR packages are all built from source[1], there's no index available for the _installed_ files. So I think the answer is no.

[1] Whether they actually compile anything is not really the issue, because there's no feasible generic way to tell if they do -- so from the package management point of view they all are.

**Comment by Jguer** [comment]
@grandchild is correct, there is sadly no centralized AUR filelist and technically speaking it would be very complex to implement such a system
