### ISSUE TITLE
Cached aur packages for newly bootstrapped filesystem.

### ISSUE THREAD

**Issue by pauldotknopf** [Jguer/yay#135]
My system is currently setup to use [Darch](https://godarch.com/).

I have a Travis-CI repo setup that builds and deploys fresh operating system images for me to boot.

To cut down on build time on the CI server, I'd like to cache downloads and AUR packages.

On each build, I intend on mounting a cached ```/var/cache/pacman/pkg``` directory. This will save time on downloading of packages from official repositories.

But what about the AUR? I'd like to only clone/build/install if there is a new package version. Otherwise, I'd like to get install a cached package.

Any thoughts?

**Comment by Morganamilo** [comment]
This was actually a thing I was working on before my laptop decided to brake. It will be added eventually although it don't really have the time to work on much right now.

Also the default build dir is due to be changed to `~/.cache/yay` Although with your use case you would probably want something more like `/var/cache/yay` maybe even with a dedicated yay user. Root can not use makepkg and regular users wont have write perms in /var, unless you mount it to /var/tmp of course.
