### ISSUE TITLE
Hide newer packages as AUR

### ISSUE THREAD

**Issue by cryptolukas** [Jguer/yay#1355]
**Is your feature request related to a problem? Please describe.**
It's kind of annoying to see every time the error of known packages that newer than AUR ones.
``` 
:: Searching AUR for updates...
 -> visual-studio-code-insiders: local (1597991132-1) is newer than AUR (1593414285-1)
```

**Describe the solution you'd like**
I would like to have a list or config value to hide this package

**Describe alternatives you've considered**
Don't use applications that have in application updates ;)

**Comment by Morganamilo** [comment]
I'd say the best way to hide the warning is to fix the issue. Usually this comes about from pkgbuilds with bad pkgver functions.

**Comment by Morganamilo** [comment]
Actually looking at this again. I'm guessing -insiders is some sort of -git like package. I'm pretty sure we hide the warning for those kind of packages. I guess -insiders should be added to the list.

**Comment by grandchild** [comment]
This pesky visual-studio-code-insiders package comes up again and again... Maybe it warrants special treatment?
I dislike the addition of `-insiders` to the list of VCS package identifiers because it's sooo marketing-y, ugh.

Maybe this needs a larger discussion about a generic term and suffix for these kind of packages (I simply assume there are others). That would have to be had in the Archlinux/AUR context though. Ideally that would entail
* introducing such a generic suffix
* AUR helpers & others supporting it like `-git`, `-hg`, `-svn` and others
* packages adopting it in their names

**Comment by hood** [comment]
Commenting as I'm facing this issue rn (`visual-studio-code-insiders: local (1602222655-1) is newer than AUR (1600675246-1)`) and the maintainer words about it are "seems like your AUR helper doesn't run the pkgver function before comparing versions. That's not really a problem with this package, you should report it to yay.". As for the `-insiders` part, I can tell you that VSCode insiders has some differences to the "main" version (some ui differences, including the logo's color), so imho it makes sense to leave the name as it is.

**Comment by cryptolukas** [comment]
What is the plan to do here?

**Comment by Jguer** [comment]
I guess we can add `-insiders` to the devel list.. at least until some better idea comes along
