### ISSUE TITLE
Error on download when parses info from SCRINFO

### ISSUE THREAD

**Issue by zoedsoupe** [Jguer/yay#1383]
#### Affected Version
yay v10.0.4 - libalpm v12.0.2

**Describe the bug**
I cannot install some packages that need to download source code, like insomnia, spotify, network-manager-applet

**To Reproduce**
`yay -S insomnia`

**Expected behavior**
Install those packages without error.

**Output**

```sh
yay -S insomnia      
:: There are 4 providers available for insomnia:
:: Repository AUR
    1) insomnia 2) insomnia-bin 3) insomnia-git 4) insomnia-src 

Enter a number (default=1): 1
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  insomnia-2020.3.3-1

  1 insomnia                         (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/1): insomnia
  1 insomnia                         (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: insomnia

==> ERROR: An unknown error has occurred. Exiting...
error downloading sources: insomnia
```

**Comment by grandchild** [comment]
Works for me... maybe you have network issues? What happens when you download the source directly?:

```shell
wget https://github.com/Kong/insomnia/releases/download/core%402020.3.3/Insomnia.Core-2020.3.3.deb
```

**Comment by grandchild** [comment]
Also, @Mdsp9070, because this _sounds_ more like an issue with network/_makepkg_, please be aware that any AUR helper like _yay_ is just a helper, and offers no guarantees. You **must** be familiar with the manual package build process as described here:

https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_and_upgrading_packages

You should **always** be able to install packages manually like that!

Tip: Just install the next few packages you need without _yay_ and manually instead, so you know exactly what _yay_ does for you. This way you will learn on what level to debug your problems. (Because the download problem seems like something that would have occurred with plain _makepkg_ as well, and so it's not strictly a yay issue.)
