### ISSUE TITLE
Downloading with self-signed certificate

### ISSUE THREAD

**Issue by Sohimaster** [Jguer/yay#1386]
program does not working at corps with self-signed certificates, add ssl verify option to avoid this

**Comment by Sohimaster** [comment]
https://github.com/Jguer/yay/issues/137 link to this ticket, I use pacman

**Comment by grandchild** [comment]
Hi there, I see you found the original ticket. So it seems there is really no need for this duplicate ticket then. The maintainers are clearly aware of the issue already, since they even commented on #137 too.

In general it's not much use having multiple tickets for the same issue, it only creates confusion.

One option you have to signal your need for a solution is to :+1: the original issue via the reaction button at the top right of the original issue message -> https://github.com/Jguer/yay/issues/137#issue-294622355.

I get that it can be frustrating seeing an issue that's giving you problems not resolved for a long time, but remember, the people who are writing this software are doing this in their spare time!

**Comment by grandchild** [comment]
On the other hand, the other isse is closed, so maybe this issue does have merit...

**Comment by Sohimaster** [comment]
@grandchild, the issue you are talking about is marked as bug however it's common network-paired software functionality. Furthermore, this issue is closed

**Comment by Sohimaster** [comment]
that's why I created this issue.

**Comment by Sohimaster** [comment]
I have no expertise in GoLang, but I can try to implement this option, if u can support me somehow if i need

**Comment by grandchild** [comment]
I already started implementing it. The PR is linked above :)
