### ISSUE TITLE
Upgrading AUR packages with circular dependencies.

### ISSUE THREAD

**Issue by kucksdorfs** [Jguer/yay#1457]
### Is your feature request related to a problem? Please describe.

I am not sure if this requires a feature or a bug. A feature seems more appropriate at the moment.

Currently I cannot do an upgrade of the zfs-dkms and zfs-utils packages. I think the problem is because they are both dependencies of each other. However if I uninstall and then reinstall them it installs just fine.

### Describe the solution you'd like

I would like to not have to uninstall packages that have recursive dependencies.

### Describe alternatives you've considered

Uninstalling the package and then re-running the installation from yay.

### Additional context

Not applicable.

**Comment by grandchild** [comment]
(This issue should be renamed from _"recursive"_ to _"circular"_ dependencies)

I would have expected `yay -Syu --batchinstall` to do the trick, but it didn't. 🙁 

Why doesn't `--batchinstall` help with this? I guess it's because yay does its own dependency checking even after packages have been built? Why not defer the install-time dependency checking completely to `pacman -U` when using `--batchinstall`?
