### ISSUE TITLE
Yay ignore SUDO_ASKPASS

### ISSUE THREAD

**Issue by Crandel** [Jguer/yay#1494]
### Affected Version

yay v10.2.1 - libalpm v12.0.2

### Describe the bug
I use gnome-keyring together with secret-tool from [libsecret](https://archlinux.org/packages/core/x86_64/libsecret) 
I unblock gnome-keyring and all tools ask for sudo password from secret tool. Pacman works fine too. But yay ignore this variable somehow and ask sudo password from stdin every time I need to install packages 

### Reproduction Steps
1. export SUDO_ASKPASS
2. install package
3. sudo password will be asked

### Expected behavior

No password required

**Comment by grandchild** [comment]
Pacman works fine because it never calls sudo, it's called _with_ sudo.

The yay issue is probably an environment thing. [pkg/settings/exe/exec.go](/Jguer/yay/blob/next/pkg/settings/exe/exec.go#L36) should probably set `cmd.Env = os.Environ`.

**Comment by grandchild** [comment]
Digging further into the `sudo` manpage, `SSH_ASKPASS` is only taken into consideration when one of two things happens:
* the sudo process is not connected to a terminal (this is not the case in yay, it is connected)
* you call sudo with the `-A` flag

The problem is that if you set `-A`, sudo will exit with error if `SSH_ASKPASS` is not set. There seems to be no way to say "Use SS_ASKPASS if available, but fallback to stdin if not".

The solution might be either:
* pass the environment and run `sudo -A` first, on failure, try again without `-A`, or
* check the environment for the presence of an `SSH_ASKPASS` key, and if it is there, call sudo with `-A` else without.

**Comment by Crandel** [comment]
@grandchild Yes, you are right, I'm using alias for this
```
export SUDO_ASKPASS=ask_sudo
alias sudo="sudo -A"
```
2 option sounds good for me and should be easy to implement

**Comment by benjarobin** [comment]
yay does not need any modification. Tested using: 
```
export SUDO_ASKPASS=ask_sudo
yay -Sy --sudoflags "-A"
```
You just have to make the configuration permanent using the following command: `yay --sudoflags "-A" --save`

**Comment by Crandel** [comment]
Thank you @benjarobin! It works!
