### ISSUE TITLE
yay 11.0.1 fails to switch to su instead of sudo

### ISSUE THREAD

**Issue by adrinjalali** [Jguer/yay#1614]
### Affected Version

``` bash
$ yay --version
yay v11.0.1.r0.g52efaeb - libalpm v13.0.1
```

### Describe the bug
`yay` fails to switch to `su` instead of `sudo` when run from a non-sudoer user. Seems like it should have been fixed in https://github.com/Jguer/yay/commit/c8fcdeae5b168d7a3eb3d805ee823d0fd5658b85

``` bash
$ yay
[sudo] password for USER: 
Sorry, try again.
[sudo] password for USER: 
Sorry, try again.
[sudo] password for USER: 
sudo: 3 incorrect password attempts
 -> error installing repo packages
```

### Output

Current config:

``` bash
$ yay -Pg
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/USER/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false
}
```

**Comment by Jguer** [comment]
Hey @adrinjalali `yay` chooses only one privilege elevator for its session, and if `sudo` is installed it will use that instead of falling back on one of its counterparts. 

That's what https://github.com/Jguer/yay/commit/c8fcdeae5b168d7a3eb3d805ee823d0fd5658b85 did. 

I am changing the label of your issue to `feature_request`. My only requirement for it would be that it doesn't require the user to be pinged for a password to verify if it's' `non-sudoer user`

**Comment by adrinjalali** [comment]
Thanks for the quick response. `timeout -k .1 .1 sudo -v` and checking the output of the process should be a good place to start I guess. The process returns 1 if the user can't run `sudo`

**Comment by Jguer** [comment]
> Thanks for the quick response. `timeout -k .1 .1 sudo -v` and checking the output of the process should be a good place to start I guess. The process returns 1 if the user can't run `sudo`

a user that can run sudo but with a password prompt will also get `status==1` with this command

**Comment by Rogach** [comment]
Isn't using `--sudo=su` better, to explicitly ensure that the correct binary is selected? Trying to implement autodetection of such features is usually fraught with peril.

**Comment by adrinjalali** [comment]
Yes it is. I had always failed to get it work cause I forgot to do `yay --sudo=su -Syu` instead of `yay --sudo=su`. I'm perfectly happy with the option I have now. Feel free to close the issue if you think it doesn't need a fix. I was confused since I came from `yourt` and that automatically switches to `su` when needed even if `sudo` is installed.

**Comment by benediktsatalia** [comment]
>Hey @adrinjalali yay chooses only one privilege elevator for its session, and if sudo is installed it will use that instead of falling back on one of its counterparts.

@Jguer How can `sudo` not be installed if `yay` requires `base-devel` which depends on `sudo`? I tried deinstalling `base-devel` but then got a lot of errors when trying to install anything. Maybe I missed this but I also didn't find anything about runtime requirements of `yay` (since `base-devel` is only documented as required to install `yay`).
