### ISSUE TITLE
Disable the "enter packages you don't want to upgrade" prompt by default

### ISSUE THREAD

**Issue by mvdan** [Jguer/yay#170]
I want to confirm the final action, but I don't want to be prompted twice. This feature is an addition on top of what people are used to with Pacman, so I think it should be behind an upgrade flag or a config value.

**Comment by notramo** [comment]
I would prefer a config option.

**Comment by Jguer** [comment]
With noconfirm you get no prompts, 
Without noconfirm you get 2 prompts.

Personally I would prefer to have just one but I know some people like to decide after seeing the size delta. 

Config option seems overkill, it's a design decision and I think we're a bit too tight on column space to show the size delta of each package.

So I see 3 options: 
1. Keep as is
2. Reduce to one prompt and pass noconfirm to Pacman
3. Reduce to one prompt and show total size delta and total download size (for mobile data purposes) before the menu.

**Comment by notramo** [comment]
In that case I would prefer the second.

**Comment by freed00m** [comment]
Can somebody please explain to me how the noconfirm is set?
I am on version 2.350 and from reading changelog it says ita should work as expected.
No mention in man pages, nothing in readme and if I add noconfirm bool to my config, it's ignored. :I ? sorry for bragging but I am clueless.

**Comment by Morganamilo** [comment]
At one point noconfirm was an option in the config file, it was later removed. Just use the flag if you insist but noconfirm is not really recommended anyway, because you'll miss all sorts of important info and wont view any of the pkgbuilds.

**Comment by freed00m** [comment]
@Morganamilo, ah ok , thx for reply I thought something has changed. 
I am using a wrapper called pacui that optionally uses yay, since it pulls package information faster than pacman or yaourt and generally has a nicer output. 

I used to have yaourt config to skip pkgbuilds it botered me only once. This time I am interupted twice. 

Shame pacui isn't using any config file for optional arguments to be used if I wanted this noconfirm behavior. 

I'll probably have to discontinue my yay usage :(

**Comment by Morganamilo** [comment]
We still support `--noconfirm` just like pacman and probably every other AUR helper. 

I've never used pacui but I did just install it and both `pacui --help` and `man pacui` gave me nothing with is quite saddening.

I would expect pacui to have a way to pass flags to aur helpers kinda like how `--mflags` passes stuff to `makepkg`. Or even an environment variable for `$AURHELPER` and `$AURFLAGS`.

I have no idea if either of these are supported as there is no documentation.

**Comment by Morganamilo** [comment]
I did find the documentation which requires starting pacui and pressing `h`. Although it does not address my above point and doesn't seem very pacui specific.

**Comment by freed00m** [comment]
@Morganamilo pacui's pretty dumbyfing the update, install process of packages with numbers. It only provides few option with predefined commands that are sequentially executed with primitive logic like, If yay exist use yay else pacman and stuff. I'll query the pacui developer about the variable.

Thx

**Comment by samosaara** [comment]
I wanted to resurrect this issue since this has becoming quite annoying for me too, the solution I was thinking about implementing was adding an `--all` flag in order to specifically skip the number prompt... But the cool thing is that doesn't need to be limited to the update part, and skip all number menus. E.G `yay jdk --all` to install EVERYTHING found by the search.

But then it kinda feels a little inconsistent and would ask for a similar mechanisms to the PKGBUILD and Clean build prompts? Or better yet, make it even more generic to be something like `--default-answer none`?

**Comment by Morganamilo** [comment]
A similar thing was talked about over at #226. I still haven't done anything about it because I don't have a clear idea for how exactly it should be.

**Comment by Morganamilo** [comment]
`yay --answerupgrade none --save` will make Yay answer `none` when it asks what packages to skip. The menu still shows but there's no user interaction needed.
