### ISSUE TITLE
Add an install reason on explicitly installed packages

### ISSUE THREAD

**Issue by joaonunatings** [Jguer/yay#1721]
### Is your feature request related to a problem? Please describe.

After installing a bunch of packages I find myself clearing some of them but can't find the reason for some.

### Describe the solution you'd like

When querying local packages i.e.: `yay -Qi <package_name>` it would be cool to have a section called for example _Install reason:_ where it would have a user inserted string with the install reason for that package. This user string would be added when installing a package i.e.: `yay -Syu <package_name> --reason 'Package for this/that'`

### Describe alternatives you've considered

Using a yay alias which not only calls yay but also a script that does that (I haven't done this, but I consider this to be useful enough to be added to yay)

**Comment by grandchild** [comment]
This would be a really cool feature indeed, but it's not something `yay` can provide. It would require a pacman database change, and so it would be a `pacman` feature. You could ask on the pacman mailing list: https://lists.archlinux.org/listinfo/pacman-dev -- or better yet, search for previous people asking for the same feature.

**Comment by DrKittens** [comment]
Can kind of meet the usecase suggested by OP with the Required by / Optional for fields and dependancy searches

ex:
Look at installed packages that could be the reason why a dep is there:
`pacman -Qi linux | egrep 'Name|Required By|Optional For'`

Do a reverse dependancy search against all official packages:
`pacman -Sii linux | egrep 'Name|Required By|Optional For`

~~If you want to check aur too just do yay -Sii.. instead of pacman -Sii it will take a while though, egrep is optional just formats it nicely~~

Above doesnt actually work for yay / the aur, as the AUR doesnt publish those fields in a query response for some insane reason.

 Simplest bet would be a shell alias like..
```
 openaur ()
{
	/usr/bin/firefox $(/usr/bin/yay -Sii $1 | egrep -o 'https?://aur.archlinux.org/packages[^ ]+')
}
```

invoked like `openaur packagename` where packagename is the aur package you're curious about requirements for

then a manual review of the "Required By" section 

Edit 2: if we dont care about checking if the aur package exists / spell check a dumb funciton that just concatenates $1 onto the end of aur.archlinux.org/packages/ would also work

**Comment by grandchild** [comment]
@DrKittens I think OP was talking about explicitly installed packages. In most cases these aren't required for anything, as they are at the top of their dependency tree. I think what they asked for is kind of a free text field that you could write something like "just trying out Foo, deleteme" into, so your future self knows whether it's important or not.

**Comment by Jguer** [comment]
I agree with @grandchild , this would be a better request for pacman-dev
