### ISSUE TITLE
Possbile PKGBUILD parsing issue?

### ISSUE THREAD

**Issue by Mayurifag** [Jguer/yay#176]
Wanted to install https://aur.archlinux.org/packages/flameshot/

I tried `yay -S flameshot-git`, but got an error:

```
==> Resolving Dependencies
map[make qt5-tools:{}]
Could not find all Deps
```

And then I installed the package with the help of yaourt, everything was just fine. 
Thanks for the development!

EDIT: actual pkgbuild:
```
# Maintainer: xyzzy <628208@gmail.com>

pkgname=flameshot
pkgver=0.5.0
pkgrel=3
pkgdesc="Powerful yet simple to use screenshot software"
arch=('i686' 'x86_64')
url="https://github.com/lupoDharkael/flameshot"
license=('GPL')
depends=('qt5-base')
makedepends=('make' 'qt5-tools')
provides=('flameshot')
source=("https://github.com/lupoDharkael/flameshot/archive/v${pkgver}.tar.gz")
sha256sums=('32d593c14c37286d9f64873c4ef9a07eb084723c92b2280d5c22152547c1e3f0')

build() {
  cd "${srcdir}/${pkgname}-${pkgver}"
  qmake
  make
}

package() {
  cd "${srcdir}/${pkgname}-${pkgver}"
  install -Dm755 "./flameshot" "${pkgdir}/usr/bin/flameshot"
  install -Dm644 "./dbus/package/org.dharkael.Flameshot.service" "${pkgdir}/usr/share/dbus-1/services/org.dharkael.Flameshot.service"
  install -Dm644 "./dbus/org.dharkael.Flameshot.xml" "${pkgdir}/usr/share/dbus-1/interfaces/org.dharkael.Flameshot.xml"
  install -Dm644 "./docs/desktopEntry/package/flameshot.desktop" "${pkgdir}/usr/share/applications/flameshot.desktop"
  install -Dm644 "./docs/desktopEntry/package/flameshot-init.desktop" "${pkgdir}/usr/share/applications/flameshot-init.desktop"
  install -Dm644 "./img/flameshot.png" "${pkgdir}/usr/share/icons/flameshot.png"
}
```

**Comment by Morganamilo** [comment]
For some reason Yay fails to find the `make` package that's in the official repos. Quite weird, needs some looking in to.

**Comment by Morganamilo** [comment]
Okay after looking at the AUR page it seems like you did not post the correct pkgbuild. The pkgbuild you sent is for flameshot while you said you were installing flameshot-git. flameshot installs fine with yay. flameshot-git is broken because of this line.
```bash
makedepends=('make qt5-tools')
````

make and qt-tool are quoted together so technically this package depends on a pkg called `make qt5-tools`. You can see the web page really doesn't like this.

![image](https://user-images.githubusercontent.com/16593899/36563117-01435350-1811-11e8-9ba4-5f7eb03b0960.png).

This is not Yay's problem it's flameshot-git's.

That being said Yay doesn't give the correct error message so there's still something to fix there.

**Comment by Morganamilo** [comment]
The pkgbuild has been fixed now so it should install just fine with Yay now.
