### ISSUE TITLE
[Q] How to mark package as devel?

### ISSUE THREAD

**Issue by carbolymer** [Jguer/yay#1797]
Not an issue but a question. 

I'm using https://aur.archlinux.org/packages/neovim-nightly-bin which is a neovim nightly build. It does not have `-git` suffix, which I presume `yay` is using for detection if the package is a development one. So obviously, when doing `yay -Syu --devel`, `neovim-nightly-bin` is skipped - but I would like it to be included.

The information about git HEADs of devel packages is stored in `vcs.json` file, but I don't feel that modifying internal yay files by hand is the right way.

How can I mark any package as development package?

**Comment by grandchild** [comment]
`yay` treats packages with a `-git` suffix as devel packages. Currently there's no user-facing way to add another suffix.

However the manpage does contain an example for how to do this locally on your system:
```shell
pacman -Qmq | grep -Ee '-(cvs|svn|git|hg|bzr|darcs)$' | yay -S --needed -
```
To add all "nightly" packages (`-bin` or otherwise) to the list I'd suggest something like this (as an alias perhaps?):
```shell
pacman -Qmq | grep -Ee '-(cvs|svn|git|hg|bzr|darcs|nightly(-bin)?)$' | yay -S --needed -
```

**Comment by AladW** [comment]
> The information about git HEADs of devel packages is stored in vcs.json file, but I don't feel that modifying internal yay files by hand is the right way.

How do you expect to store git HEAD if the package does not use git?
