### ISSUE TITLE
Print the bell character (\007) before any prompt

### ISSUE THREAD

**Issue by vpatkov** [Jguer/yay#1853]
When running `yay -Syu` and switch to another window to work, it would be very helpful if yay prints the bell character in terminal whatever it asks for user interaction. AFAIK it has no any drawbacks.

**Comment by Jguer** [comment]
I think this would be specially useful for su password prompts

**Comment by jdholtz** [comment]
Hey @Jguer. I would like to submit a fix for this. I've been playing around with this and it seems like yay specifically prompts in two places: `GetInput` and `ContinueTask`. Are there any other places I'm missing?

`sudo` has the `-B` flag that can be added to the `sudoflags` configuration option. This can be added to the FAQ in the README so people know how to be notified of password prompts (users would have to figure out how to do the same thing if they use something different than sudo). I looked at adding this within the code itself, but it doesn't seem like yay can detect whether `sudo` will actually need to prompt or not (with the timeout). Yay can also use the `-p` flag from sudo to use a custom prompt that includes the bell character, but that also might have unintended side effects. 

However, I'm unsure how to use the bell when pacman prompts. I don't think pacman has special configuration for this. Any thoughts on this? One idea is to check if the pacman command will prompt beforehand (check for -S, -Rns, etc.) and print the bell, but the bell will be printed before the pacman command executes which means the user has to wait for it to prompt still. 

Last, would you want me to include a config option for this? This way, people can disable it if they do not like it for whatever reason.

**Comment by vpatkov** [comment]
For some reason, @allanmcrae [rejected](https://bugs.archlinux.org/task/41188) this feature. Pacman allows you to bypass any questions (`--noconfirm`), but don't allow to notify the user about the questions. Yes, it doesn't time out, but "Enter a selection" is the last thing I want to notice before shutting down my PC.

Unfortunately I can't see any clean solution from Yay's perspective. Sniffing the pacman's output for questions is very dirty, not reliable, and depends on locale.

**Comment by jdholtz** [comment]
I did file a bug report for pacman [here](https://gitlab.archlinux.org/pacman/pacman/-/issues/7) (I didn’t see the 8 year old patch). I asked for clarification as to his reasons for rejecting it, so we’ll see what he says.

**Comment by Lazerbeak12345** [comment]
It's been a year - no reply from upstream.

This feature is particularly useful for me so it can ring the bell when I need to do something, and then I can read over what it's been doing, and then act accordingly. All without sitting there waiting for very slow downloads, AUR compilation & etc.

Providing a feature to ring the bell is an _accessibility_ feature, and _improves_ user experience. Any argument that doing something else instead of staring at a loading bar is "unattended upgrading" is a baffling one to me - considering how well pacman and yay both log. My computer can't and shouldn't try to stop me from doing something else while I wait for a long-running process - but I think it _should_ let me know when it becomes interactive.

Side note: I can't easily make a comment on the upstream issue, since they've locked down interaction due to an unfortunate spam problem.

**Comment by jdholtz** [comment]
> Side note: I can't easily make a comment on the upstream issue, since they've locked down interaction due to an unfortunate spam problem

Hm, possibly try the Archlinux subreddit? I’ve had Allan reply to one of my Reddit posts before so I know he is active (or, at least, was active) on it occasionally.

**Comment by jakkdl** [comment]
I think even if upstream doesn't implement this, yay can still do it for the prompts it generates as long compile times have me much more likely to switch to another workspace and forget. It's additionally possible to get a visual bell on sudo prompts (e.g. by setting `SUDO_PROMPT`) which addresses some of the `pacman` prompts as well.

**Comment by Lazerbeak12345** [comment]
I've had electron installed from the AUR before - and I can attest that I'll be doing something else for those several hours that it and other packages take to compile.
