### ISSUE TITLE
The Installation process in README is obsolete

### ISSUE THREAD

**Issue by hopeseekr** [Jguer/yay#1936]
Since the reworking of the build system, one can no longer issue the `makepkg` command, thus the README is out of date / obsolete.

**Comment by Jguer** [comment]
> Since the reworking of the build system, one can no longer issue the makepkg command

Can you link me to this?

**Comment by grandchild** [comment]
I think @hopeseekr cloned the wrong repo 🙂.
@hopeseekr look closely at the URL in the README, it's not this repo, it's the AUR package.

**Comment by Jguer** [comment]
Fair point @grandchild , had not even thought of that :joy:. Closing

**Comment by grandchild** [comment]
The README could still be improved regarding this, with a small comment next to the `git clone` line. If you want, @Jguer, I can whip something up tomorrow.

**Comment by Jguer** [comment]
@grandchild please go ahead

**Comment by hopeseekr** [comment]
I'm still so confused.

In order to install `yay`, I have always `git clone` the repo (i thought I had cloned **this** repo), then `makepkg -si`.

However, for the first time in many years, when I tried that, it didn't work because there is no `PKGBUILD` in this repo. Instead, I had to do `make; sudo make install`.

I thought, ok, that's weird, but it looks like they updated their build / install system from `makepkg` to `make`, so I created the README PR.

So, if this isn't the right `PKGBUILD` repo, you should probably mention that, in the README, so we can all go to the right one.

If this is the right repo to clone, then you should alter the README to use the `make` code. 

If the README is meant only for the `makepkg` repo, maybe rename it and create a new README.md specifically for this repo?

**Comment by grandchild** [comment]
I can understand the confusion, really. I hope it does not come across as us trying to gaslight you or anything. I assure you it's in all likelihood a very simple misunderstanding:

There are 4 places in the README that mention `makepkg`. You are probably referring to the first one:

>     ### Source
>     The initial installation of Yay can be done by cloning the PKGBUILD and
>     building with makepkg:

I think the confusion comes from you taking "cloning the PKGBUILD" to mean "clone this repo" -- which it does not. It refers to the AUR repo. We'll come to that now:

All the other occurrences of `makepkg` are inside example shell command sections:

>     pacman -S --needed git base-devel
>     git clone https://aur.archlinux.org/yay.git
>     cd yay
>     makepkg -si

>     pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si


>     pacman -S --needed git base-devel
>     git clone https://aur.archlinux.org/yay-bin.git
>     cd yay-bin
>     makepkg -si

You'll notice that _all_ these sections _explicitly_ mention the AUR repo at **`https://aur.archlinux.org/yay.git`** or **`https://aur.archlinux.org/yay-bin.git`** -- and **not** to the URL of this repo. I think this is were your confusion stems from. I wager you didn't copy-and-paste, but followed the instructions by more or less typing them yourself.

I do agree that this misunderstanding is entirely understandable. Both places are git repos. And also the phrasing "cloning the PKGBUILD" could probably be a bit clearer.

Your PR changed the whole process however, because cloning _this_ repo and running `make` builds a binary and not a package! This is a big difference because a binary is just that, and a package will be updated over time, which is highly desirable.

I hope I could clear up your confusion. I will try to make the README a bit less ambiguous around this.
