### ISSUE TITLE
Search does not find npth

### ISSUE THREAD

**Issue by AndydeCleyre** [Jguer/yay#23]
`pacman -Ss npth`
```bash
core/npth 1.4-1 [installed]
    New portable threads library
community/mingw-w64-winpthreads 5.0.2-1 (mingw-w64-toolchain mingw-w64)
    MinGW-w64 winpthreads library
```
`yay -Ss npth`
```bash
aur/npth-git 1.2+3_ga49a061-1 (2) 
A library to provide the GNU Pth API and thus a non-preemptive threads implementationA IPC library used by some GnuPG related software (git version).
aur/mingw-w64-winpthreads-git 4.0.rc1.r7.gc440466-1 (5) (Orphaned) 
MinGW-w64 winpthreads library
community/mingw-w64-winpthreads 5.0.2-1 (mingw-w64-toolchain,mingw-w64) 
MinGW-w64 winpthreads library
```

This one's really interesting.  `1.115`

**Comment by Jguer** [comment]
That's a regression I found while searching for linux headers. (check `yay -Ss linux headers` and `pacman -Ss linux headers`

Fixed in https://github.com/Jguer/yay/commit/a20646fa246c00b73ddffa520112760e15e9dace.
I've been avoiding releasing yay 2 early to avoid this type of bugs. But at the end of the month the dev version should be stable.
