### ISSUE TITLE
melonds-git isn't recognized as devel

### ISSUE THREAD

**Issue by hcorion** [Jguer/yay#261]
#### Affected Version

```bash
yay -V            
yay v4.505.r45.g44f2da3
```
#### Issue
PKGBUILD:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=melonds-git
I assume it has to do with
```
"${_gitname}::git://github.com/StapleButter/${_gitname}.git"
```
I am the maintainer of the package, so if this is a WONTFIX, I can adjust the pkgbuild for yay.
#### Steps to reproduce
1. `yay -S melonds-git`
2. `yay -Syu` (Notice how melonds-git is under aur/melonds-git, instead of devel/melonds-git)
3. Profit??

**Comment by Morganamilo** [comment]
`aur/melonds-git` means the version on the AUR is newer than your local version.
`devel/melonds-git` means a newer version was found by checking git commits.

devel packages can still get `aur/` updates when the pkgbuild is updated.

Something is wrong with your package though. `pkgver()` resolves to `0.6.aab0030-1` while the version on the aur is `0.6.3881b26-1`. the version on the AUR is a newer version according to vercmp so Yay will always prompt for an update.

The fix is to use a proper `pkgver()` such as:

```sh
pkgver()
{
  cd "${_gitname}"
  printf "%s.r%s.%s" "${_releasever}" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}
```

**Comment by Morganamilo** [comment]
Looking at it more I can't tell where you get `_releasever=6` from. I would probably drop it entirely.

**Comment by hcorion** [comment]
Alright, thanks for the advice, I'm pretty sure I copied it from a different package.
_releasever=-0.6 is because that's what the version number is, the creator of the application doesn't do git tags or anything, so I'd have to sed some files to get it, which I don't want to bother with.
