### ISSUE TITLE
yay -Syu upgrades to -git package instead of release.

### ISSUE THREAD

**Issue by YamashitaRen** [Jguer/yay#359]
```
$ yay --version
yay v5.675.r25.g6118a9f
```

How to reproduce : 
1) Enable [archlinuxcn](https://wiki.archlinux.org/index.php/unofficial_user_repositories#archlinuxcn) repo.
2) Install an old pcsxr version (1.9.94-2 in my case)
3) yay -Syu

What happens : 
yay wants to update locally built (from AUR) pcsxr to archlinuxcn's pcsxr-git package.
I guess it does this because (again a guess) archlinuxcn's pcsxr-git provides "pcsxr".

What should happen : 
yay should update pcsxr to AUR's pcsxr.

**Comment by Morganamilo** [comment]
Yeah seems a little weird. `Pacman -S providers` will find and install a package that provides what you entered. `java-environment` is a good example of this.

As an extension of this `yay -S pcsxr` installs `pcsxr-git` because it provides `pcsxr` and we always prioritise repo packages over AUR packages.

It seems the same thing is happening during `-Syu` when it shouldn't.

**Comment by Morganamilo** [comment]
Should be fixed now if you wanna give it a try.

**Comment by YamashitaRen** [comment]
Yep, fixed here !
Thanks :)
