### ISSUE TITLE
Don't use vercmp for -git packages

### ISSUE THREAD

**Issue by Streetwalrus** [Jguer/yay#392]
#### Affected Version
yay v6.727.r13.ge6b557f

#### Issue
Due to the nature of commit hashes, vercmp is unreliable to determine whether the PKGBUILD version is more recent than the installed version.
Example:
```
aur/python-telethon-aio-git  20180506.dffbd2d-1      -> 20180506.41f0e0c-1
```
This is wrong, see the relevant commit log [here](https://github.com/LonamiWebs/Telethon/commits/dffbd2d689c1363ec48fd0d79052b815fe06bc0a).

**Comment by Morganamilo** [comment]
This is a problem with the package. You should never just use commit hashes for a pkgver. For example if you look at the Yay's version in your message we have `r13` before the commit hash. This means 13 commits since the last release and is a way to ensure `r14.ghash` is always never than `r13.ghash`.

The wiki has info on the suggested format here https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver.28.29_function

When it comes to actually updating -git packages that's a different story and comes under `--devel`.

**Comment by Streetwalrus** [comment]
>This is a problem with the package

I agree, but this is a problem for a number of packages in the AUR, and fixing all of them isn't really an option.

**Comment by Streetwalrus** [comment]
Yeah I'm going to fix my own packages. The problem is this doesn't work for repos that do not have any tags in them, but that can easily be worked around.

**Comment by Morganamilo** [comment]
```sh
printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
```

Works for repos without tags, you get `rx.ghash` instead of `version.rx.ghash` which makes sense because if there are no tags then there's probably not a version. If you know the version you can always hard code it into the printf statment.

Then when/if a repo finally does get tags you switch to the other format and add an epoch.
