### ISSUE TITLE
Incompatible with `proxychains`

### ISSUE THREAD

**Issue by F-TD5X** [Jguer/yay#429]
#### Affected Version
yay v6.777

#### Issue
Incompatible with proxychains.

Log:
```
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.12
:: Querying AUR...
Get https://aur.archlinux.org/rpc.php?arg%5B%5D=anbox&type=info&v=5: dial tcp 224.0.0.1:443: connect: network is unreachable
```

But I am sure the proxy is valide.

#### Steps to reproduce
1. simply run `proxychains yay -S foo`

**Comment by Jguer** [comment]
I just tried it, I get exactly the same error.  As a quick fix disabling `proxy_dns` worked, although I guess that's not a choice for some.
```
# if the proxified app does a DNS request, we will return an IP from that range.
# on further accesses to this ip we will send the saved DNS name to the proxy.
```
I'll try and check it out but generally this connection type stuff goes really really upsteam to the `net/http`

**Comment by afg984** [comment]
See also: https://github.com/rofl0r/proxychains-ng/issues/199#issuecomment-340183417

**Comment by Jguer** [comment]
Came across it the other day when I was researching this, makes complete sense that it wouldn't work.

but using `gcc-go` it should be possible to use `yay` with `proxychains`
```
:: Checking development packages...
[proxychains] Strict chain  ... xxxx  ...  aur.archlinux.org:443  ...  OK
 -> Orphaned AUR Packages:  multimc5
:: 1 Packages to upgrade.
1  community/firefox-developer-edition  61.0b9-1 -> 61.0b10-1
```
I've covered `gcc-go` on `yay` [here](http://blog.jguer.space/post/yaygcc/) and moving `yay` to `gcc-go` was scraped due to lower performance, in a one sample test:

I compiled `yay` using `gcc-go` and it resulted in a nice tidy 1.3M executable and `proxychains` works
Compile flags `'-s -w -O2 -Os -ffast-math'`
```
time yay -Ss linux // go
0.25user 0.04system 0:00.66elapsed 44%CPU (0avgtext+0avgdata 39344maxresident)k
0inputs+0outputs (0major+7940minor)pagefaults 0swaps
time ./yay -Ss linux //  gcc-go
1.03user 0.06system 0:01.42elapsed 76%CPU (0avgtext+0avgdata 81240maxresident)k
64inputs+0outputs (0major+13890minor)pagefaults 0swaps
```
PS: @Morganamilo `yay-gcc` 1.3M, it's impressive the difference
