### ISSUE TITLE
Could not find built package if PKGDEST is set

### ISSUE THREAD

**Issue by rodrigo21** [Jguer/yay#434]
#### Affected Version

yay v6.784

#### Issue
After updating pacman to version 5.1.0, yay can't install a package if PKGDEST is set in makepkg.conf

#### Steps to reproduce

1. Set PKGDEST to some path in makepkg.conf
2. yay -S package
3. Could not find built package ...

Maybe related to issue #333 and the change in makepkg --packagelist [behavior](https://git.archlinux.org/pacman.git/commit/?id=d8591dd3418d55c5736022ef003891fc03b953e0).

**Comment by Morganamilo** [comment]
Yay would always error, if you set the pkgdest. I have however been looking forwards to the Pacman 5.1 changes because it makes it easy the use the pkgdest, so this restriction will be lifted.

**Comment by kmac** [comment]
@Morganamilo I haven't been using yay for very long (coming over from pacaur), but I've always had PKGDEST set with yay and it's never been a problem. So I'm not understanding what you mean when you say "Yay would always error if you set the pkgdest"? 

Anyway, I had it set to 'PKGDEST=/var/cache/pacman/pkg', so that I could easily use 'downgrade'. However, it seems that there's no need to do this with yay, since I see it's copying the package tarball over when I comment out PKGDEST. Is this correct?

**Comment by Rosanna4** [comment]
> Yay, doesn't use PKGDEST at all, it expects built packages to end up in the same director as the pkgbuild, it will then run -U on that package. Changing the PKGDEST would make the package be somewhere else, causing the -U to fail.
Before Pacman 5.1 it wouldn't fail as there was always symlink created in pkgbuild directory. Everyone who had set PKGDEST before will notice breakage after Pacman 5.1 update.

**Comment by Morganamilo** [comment]
That makes sense, thanks. I guess the changed `--packagelist` is the intended replacement.
