### ISSUE TITLE
Yay can't build Molotov.

### ISSUE THREAD

**Issue by YamashitaRen** [Jguer/yay#458]
```
$ yay -V
yay v6.786.r44.gdda7a0c
```

Packaging fails because some file can't be deleted because of a permission issue. I don't have this issue when building with makepkg.
```
==> Making package: molotov 2.2.0-2 (Sun 03 Jun 2018 02:25:53 PM CEST)
==> Retrieving sources...
  -> Found Molotov-2.2.0.AppImage
  -> Found molotov
==> Validating source files with sha256sums...
    Molotov-2.2.0.AppImage ... Passed
    molotov ... Passed
==> Cleaning up...
rm: cannot remove '/home/yama/.cache/yay/molotov/src/usr/share/icons/default': Permission denied
==> Making package: molotov 2.2.0-2 (Sun 03 Jun 2018 02:25:53 PM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found Molotov-2.2.0.AppImage
  -> Found molotov
==> Validating source files with sha256sums...
    Molotov-2.2.0.AppImage ... Passed
    molotov ... Passed
==> Removing existing $srcdir/ directory...
rm: cannot remove '/home/yama/.cache/yay/molotov/src/usr/share/icons/default': Permission denied

==> ERROR: An unknown error has occurred. Exiting...
Error making: molotov
```

**Comment by Jguer** [comment]
https://github.com/Jguer/yay/issues/452

**Comment by Morganamilo** [comment]
>I don't have this issue when building with makepkg.

The issue comes when makepkg tries to clean up the files. Just running `makepkg -si` wont trigger it, but when using some of the cleanup flags like `-C` and `-c` will trigger it.

**Comment by YamashitaRen** [comment]
Argh. Sorry for the duplicate then :/

**Comment by milouse** [comment]
How works yay? What commands are used in order to build a package? The crash occurs only with yay and yay seems to not use the prepare function of the PKGBUILD. When I look at the listing above, it seems molotov is build two times? What is the difference between the first pass and the second?

The problem I have, from my maintener point of view, is that I cannot imagine how works all aur helpers in the world without a little help of your part. Thank you very much for your understanding and your help.

**Comment by Morganamilo** [comment]
Yay uses 3 `makepkg` calls.

First it calls `makepkg ---veryfysource -Ccf` This effectively downloads the sources for a package and verifies them, Yay will call this on every package to download their sources before building.

Once the above is run on every package, yay then does this for each package.

Call `makepkg --nobuild -fC` this runs `prepare()` and `pkgver()`

Then call `makepkg --packagelist` and checks each package version against the version in cache. If there is nothing in cache with the same version it builds the package via `makepkg -cf --noconfirm --noextract --noprepare --holdver`.

`--noprepare --noextract --holder` is used because the previous command did all these things, no need to do them again.

**Comment by Morganamilo** [comment]
Also I tested molotov after you tired to fix it and well, it's fixed. You do need to manually rm/chmod it to remove it from cache. But once you do that it works fine.

**Comment by YamashitaRen** [comment]
Oh damn, I thought "cleanbuilding it" (a yay option) would mean my tests would be accurate, but I didn't think that the file may stay in the cache because of the permission issue...
Sorry for the trouble, it's indeed fixed !

**Comment by milouse** [comment]
Ok cool. Thanks a lot @Morganamilo for your answers, which explain everything. Case closed :)

**Comment by Morganamilo** [comment]
Glad it's resolved. have you reported this to upstream at all? I'd be happy to make a report.

**Comment by milouse** [comment]
Unfortunately it's a closed source application. I very doubt they'll welcome our report :/ In any other case, yep, I'd have report it upstream :)

**Comment by Morganamilo** [comment]
I went to have a look myself and it's all in french. Oh well, your chmod hack fixed it anyway so all is good.
