### ISSUE TITLE
Handle `--needed` cliarg

### ISSUE THREAD

**Issue by muesli** [Jguer/yay#46]
It would be handy if yay respected `--needed` for AUR-based packages, too.

**Comment by quite** [comment]
Yes, as in going so far as to refreshing/doing a repo checkout and seeing if `makepkg` results in a newer pkgver.

**Comment by Morganamilo** [comment]
`--needed` should be handled correctly by pacman, AUR packages now have `--needed` like behaviour by default.

**Comment by muesli** [comment]
@Morganamilo It does skip installing, but it seems to always build a new package first, even if it matches the currently installed version. Shouldn't it just compare pkgvers and skip at that point?

**Comment by Morganamilo** [comment]
Are you sure its building? Yay splits the install up into two parts: download `sources=()` and  build+install. So what Yay is probably doing is downloading the sources, not building and reinstalling the built package.

I agree it shouldn't really be doing this. We need the `sources=()` so that the pkgbuild may correctly execute the `pkgver()` function. Ideally I would like a "download sources only if there's a pkgver() function" but makepkg doesn't provide this.

A little hacky but we could grep the pkgbuild for a `pkgver()` function and skip the download, or maybe a better way is to source it instead.

Most packages don't contain a `pkgver()` so I get this is pretty wasteful, I'll think about a decent solution to this.

**Comment by Morganamilo** [comment]
We rebuild the package if it doesn't already exist. I didn't think about the case where you don't have the package in cache and use `--needed`. Up until now I've just left the `--needed` flag for Pacman to handle. I'll have Yay handle `--needed` too. The above problem is still also a valid concern.
