### ISSUE TITLE
Yay cannot install meshlab

### ISSUE THREAD

**Issue by zhou13** [Jguer/yay#529]
#### Affected Version
yay v7.887.r18.ga97034f

#### Issue
````
$ yay -S meshlab
==> Error: Could not find all required packages:
    IDTFConverter (Wanted by: meshlab)
````

**Comment by Morganamilo** [comment]
`IDTFConverter` is provided by `u3d`. There's no real way for yay or any AUR helper to search for this though. You have to check the dependencies on the web page.

**Comment by Morganamilo** [comment]
@Jguer you tagged it `PKGBUILD Fault` but it's just because the rpc can't search for provides. If anything it's the rpc's fault :P

**Comment by Morganamilo** [comment]
I just wanted to clarify for anybody reading this. So they don't blame the pkgbuild. `PKGUILD/RPC Fault` is less informative cause now you don't know if it's the pkgbuild or rpc's fault. Is it worth a new tag. I don't know ¯\\\_(ツ)\_/¯.

**Comment by bartoszek** [comment]
_Sory for causing an issue, have no idea how restricted aurweb RPC interface really is ..._ :unamused: have fixed the dependency array for _meshlab_ and _meshlab-git_ .

**Comment by Morganamilo** [comment]
It's not you just the RPC. Depending on `IDTFConverter` is still the correct thing to do because there could be any number of packages that provide it. Assuming `meshlab` can work with stuff other than `u3d`.

Sure it breaks things for AUR helpers just because the RPC does not support provides but it is still the correct thing to do. And AUR helpers are not officially supported.
