### ISSUE TITLE
Can't reply Y to pacman questions

### ISSUE THREAD

**Issue by papey** [Jguer/yay#65]
Sometimes a package is replaced by another and pacman asks user is this package should be replaced or not (y/N question).

With yay, this behavior is broken and yay pass N to pacman and update fails.

**Comment by Jguer** [comment]
This is due to the default update behavior, I believe checking for package
conflicts before presenting the update menu and offering the option to
replace then should fix the problem.

On Nov 15, 2017 5:58 PM, "Wilfried OLLIVIER" <notifications@github.com>
wrote:

Sometimes a package is replaced by another and pacman asks user is this
package should be replaced or not (y/N question).

With yay, this behavior is broken and yay pass N to pacman and update fails.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Jguer/yay/issues/65>, or mute the thread

**Comment by papey** [comment]
Ok, I will try to submit a PR (not sure about the time I have to work on this)
