### ISSUE TITLE
Double confirmation when upgrade is combined

### ISSUE THREAD

**Issue by AlexWayfer** [Jguer/yay#653]
#### Affected Version

`yay v8.998 - libalpm v11.0.1`

#### Issue

Hello!

Can we somehow avoid the double confirmation for combined upgrade? Maybe pass `Y` answer to `pacman`.

I want to see colored diff between versions with AUR packages, but I don't want to make the second confirmation for colorless `pacman`s table.

Thanks.

#### Steps to reproduce

```
> yay
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Searching databases for updates...
:: Searching AUR for updates...
 -> Out Of Date AUR Packages:  downgrader  screengrab
:: 5 Packages to upgrade.
5  core/cronie         1.5.1-1  -> 1.5.2-1
4  core/e2fsprogs      1.44.3-1 -> 1.44.4-1
3  extra/cups-filters  1.20.4-2 -> 1.21.0-1
2  extra/libx11        1.6.5-1  -> 1.6.6-1
1  extra/libxss        1.2.2-3  -> 1.2.3-1
==> Packages to not upgrade: (eg: 1 2 3, 1-3, ^4 or repo name)
==> 
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Package (5)         Old Version  New Version  Net Change  Download Size

core/cronie         1.5.1-1      1.5.2-1       -0.03 MiB       0.07 MiB
extra/cups-filters  1.20.4-2     1.21.0-1       0.12 MiB       0.75 MiB
core/e2fsprogs      1.44.3-1     1.44.4-1       0.09 MiB       0.99 MiB
extra/libx11        1.6.5-1      1.6.6-1       -0.34 MiB       2.01 MiB
extra/libxss        1.2.2-3      1.2.3-1        0.05 MiB       0.01 MiB

Total Download Size:    3.83 MiB
Total Installed Size:  17.84 MiB
Net Upgrade Size:      -0.12 MiB

:: Proceed with installation? [Y/n]
```

**Comment by Morganamilo** [comment]
Personally I like it currently. It acts as the final step where yay starts the build install process. It also allows me to check what yay says is gonna happen vs what pacman says is gonna happen. Although that might just be useful for bug testing more than actual use.

On a more technical level I don't think we can hide it. That menu can contain prompts for replaces, conflicts, ignorepkg, ect. We can't just hide the main output and show the prompts and we can't just use --noconfirm/--ask because then it takes choice away from the user.

**Comment by AlexWayfer** [comment]
OK. You can close this issue if you can't do this technically without loosing important prompts (and can't pull them to `yay`).

**Comment by Jguer** [comment]
Closing this as we already tried handling some of this stuff ourselves but it's not actionable if you want to keep yay a pacman wrapper instead of a pacman
