### ISSUE TITLE
Fails to build PKGBUILD than can be built manually.

### ISSUE THREAD

**Issue by BluCodeGH** [Jguer/yay#658]
#### Affected Version
yay v8.998 - libalpm v11.0.1

#### Issue
When building `mcpelauncher-msa-git`, yay fails with `fatal: repository 'https://raw.githubusercontent.com/nlohmann/json/develop/LICENSE.MIT/' not found`, but when building manually via `makepkg -si` it builds fine.

#### Steps to reproduce
1. `yay -S mcpelauncher-msa-git`

**Comment by Morganamilo** [comment]
That's just yay being a little overzealous about trying to find git repositories. It tries to do `ls-remote` on `https://raw.githubusercontent.com/nlohmann/json/develop/LICENSE.MIT/` and git gives back a fatal error. 

For yay this is not fatal and it would just continue on, this just happens so be the last thing it does. If look look at the output you should see the package was already built and installed.

This has been fixed in -git and yay correctly knows what is and is not a git repository.
