### ISSUE TITLE
Propose a flag to show diff yaourt style

### ISSUE THREAD

**Issue by Jubijub** [Jguer/yay#660]
#### Affected Version
Any version newer than v8.918
(see FAQ entry : https://github.com/Jguer/yay#yay-is-not-prompting-to-skip-packages-during-sysupgrade-issue-554 )

#### Issue
yay -Syu used to do 2 things it no longer does : 

- offer to skip packages (still done for AUR packages)
- show a colorized diff of the versions for each package (Yaourt style)

For the time being I have mapped an alias `alias yayv 'yay -Syu --combinedupgrade'
` that launches yay the old style way, to see what is going on.
I then CTRL+C, and simply launch `yay` to ensure I launch it "the right way"

Would it be possible to automate this by proposing a flag, or even better, do it by default upon invoking ?
It's not super elegant as it involves updating the databases twice, but I think the yaourt style coloring of version difference was a big point, and I am sad to no longer have it.

**Comment by Morganamilo** [comment]
So you mean `yay --combinedupgrade --save`?

**Comment by Jubijub** [comment]
Let me see if I get this right : I read the arch wiki entry about AUR helper (in which you commented as well), where it seems that the "partial" use of pacman is discouraged. 
I probably don't understand all the technicalities, but the discussion seems to surface some risks related to the old yay ways. I believe this is what prompted the fact that `yay --combinedupgrade --save` is no longer the default behaviour (this prevents yay from having a bad score in the wiki table).

I understand I can restore the previous behaviour using that switch, but then again if it was a good thing to do I guess you'd have left it as the default behaviour, wouldn't have you?

The discussion seems to suggest the package database has an API, so I wonder if it were possible to restore the yaourt style display without having to use `combinedupgrade` .

**Comment by Morganamilo** [comment]
The problem is splitting the database refresh `pacman -Sy` and the upgrade `pacman -Su`. To know the packages which need to be updated you need an up to date database. So yay does `pacman -Sy && show packages && pacman -Su`.

People have problems with this because what if `show packages` fails? Then you end up with in a position where you could accidentally cause a partial update.

So to fulfil the native pacman (or pacman wrapper as it has gone back to), yay is not allowed to call `pacman -Sy` separately. (There's some other stuff it could do, such as refreshing to a temp db like checkupdates but that's slow and I don't really want to do it that way). So what yay does instead is `pacman -Syu && show packages` this leads to only AUR packages being shows because the repo upgrades have already happened.

Technically yay will be compliant with native pacman when doing `pacman -Sy && yay -Su --combinedupgrade`. You've just moved the problem out of yay and into your command.

> I understand I can restore the previous behaviour using that switch, but then again if it was a good thing to do I guess you'd have left it as the default behaviour, wouldn't have you?

The default is what it is because it's the safest option. If you know what you're doing there's nothing wrong with enabling it.

> The discussion seems to suggest the package database has an API, so I wonder if it were possible to restore the yaourt style display without having to use combinedupgrade.

Technically possible by using the aforementioned `pacman -Stb ~/tmp/db` hack. But then that just slows things down, requires the database to be refreshed twice and has the small possibility of the second refresh being newer, if a new database happened to be pushed between refresh 1 and 2.

>For the time being I have mapped an alias alias yayv 'yay -Syu --combinedupgrade' that launches yay the old style way, to see what is going on.
I then CTRL+C, and simply launch yay to ensure I launch it "the right way"

You've done a database refresh ctr+c'd out and then started the upgrade again, if yay did that it would not  qualify as compliment because it does a refresh separate from the upgrade.

**Comment by matleh** [comment]
Maybe split this issue in two: one for the `combinedupgrade` thing (which I don't understand) and one for the colored version diff (which I care for)?

**Comment by Morganamilo** [comment]
I tried to explain it in as much depth as I could. Showing the version diffs for repo packages without enabling `combinedupgrade` would be like trying to install a package without downloading it.

**Comment by svitoz** [comment]
I'm going to say basically what @Morganamilo said but in my words so maybe who does not get it yet finally gets it:

Using `--combinedupgrade` makes `yay` do `pacman -Sy` that refreshes pacman `sync` database that contains information about repo packages to display update information to the user. Showing upgrade summary by AUR helper is `Batch interaction 2` in the wiki table.

See also [system maintenance](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported) ArchWiki section.

Usually performing `pacman -Sy` this is not harmful if you perform system upgrade directly afterwards with `pacman -Su`. That is why you should always do pacman `-Syu` instead of `pacman -Sy`. But in case you do other operations in between like viewing build files you may change your mind, do `ctrl+c` and forget you refreshed your pacman database in the beginning. This has potential to break your system if you decide to install some package with `pacman -S application` afterwards because you can upgrade some of its dependencies while other packages were not updated and depend on library version that is gone from your system.

This is considered bad behavior on the wiki because officially unsupported tools like `yay` should not affect officially supported tools like `pacman` and since you specify `-Syu` to  `yay` it should not split this operation and do not insert its commands it in between them because they have different support status. If you do `ctrl+c` inside AUR helper - helper is responsible for exposing user to partial upgrades because it is not job of AUR helpers to handle pacman operations.

Of course feature you are descibing can be implemented some other way as explained by @Morganamilo and I think comments so far make a valid case for replacing that behaviour with something safer even if slightly less robust in the future. Arguably there is no pressure to do so because `pacman` itself does not warn you if you had cancelled `pacman -Syu` after it performed `pacman -Sy` part and such treatment of AUR helpers is relatively unfair compared to `pacman` but AUR helpers are not `pacman`.

Keep in mind that you are free to use whatever options you want understand you them or not, we just make sure as best as we can that you understand the risks these tools or their options have.

**Comment by Jubijub** [comment]
Thanks both for the detailed explanation.

I understand you are not interested in implementing any kind of database call to show the version diff.

I respect that, although I believe there is an opportunity to enhance pacman as the diff (+ news) makes upgrading experience much nicer.

**Comment by AladW** [comment]
Like I said on the wiki, if people don't implement these things of their own volition, they might as well not do it all. Anyone who installed a `pacman` wrapper agreed that, at some point, it may break their system anyway.

This is already reflected in the wiki table by having no color distinction between -Sy by default and -Sy as an option.

**Comment by Jubijub** [comment]
Thanks @AladW i didn't know about this flag.
Then my question gets simpler : is there a way to colorize the output of Pacman so that it looks like yaourt / yay with --combinedupgrade ?
