### ISSUE TITLE
Request: Equivalent of Yaourt's PKGBUILD Option: -Pi

### ISSUE THREAD

**Issue by lievin-christopher** [Jguer/yay#694]
>Build package from PKGBUILD found in a local directory..
>    −i, −−install
>        Also install the package.

**Comment by vith** [comment]
This would be very useful. When maintaining AUR packages it's easy to end up with a PKGBUILD that works due to the local environment but fails in a clean environment.

As an example, having GOPATH exported via my shell config masked the mistake I corrected here: https://aur.archlinux.org/cgit/aur.git/commit/?h=oragono&id=1cca626ee40d76faf1d70bf3428e6d892fb82ea1

But I only found the problem *after* pushing a broken PKGBUILD when I used yay to reinstall the package.

**Comment by xavier83** [comment]
I am looking for a more general ability to install from any vcs similar to python pip's https://packaging.python.org/tutorials/installing-packages/#installing-from-vcs which looks for setup.py instead of PKGBUILD.

**Comment by soloturn** [comment]
my first try not knowing it is not supported was "yay -U" - as it us used to install a local pkg file.

**Comment by YorkZ** [comment]
I'm not sure if this issue is the same as #647, but if it is, then I would be very interested in it because I'm in the exact same situation as in #647.

**Comment by soloturn** [comment]
[paru has  an experimental feature](https://github.com/Morganamilo/paru/issues/222) it is what you expect?

**Comment by lievin-christopher** [comment]
> [paru has an experimental feature](https://github.com/Morganamilo/paru/issues/222) it is what you expect?

Yes, exactly the same feature I requested

**Comment by Jguer** [comment]
Implemented as `yay -Bi` (available in `yay-git`)
