### ISSUE TITLE
[Feature request] Allow configurable default for questions

### ISSUE THREAD

**Issue by marmistrz** [Jguer/yay#734]
Currently the default answer (chosen after enter is pressed) is "None". It'd be great if it were configurable. 

I don't mean the `--answerdiff` option - this entirely disables the prompt - I still want to see the prompt, just have `All` as a default.

**Comment by izzy** [comment]
I totally second this. I'd like to have it [All] for diffs and cleanbuilds by default but still be able to select another option when I see fit instead of the current (rather problematic) default of being able to accidentally pressing enter and not seeing any diffs and just blindly installing things.

**Comment by alxpettit** [comment]
Thirded!

**Comment by marmistrz** [comment]
Please reopen.
