### ISSUE TITLE
Request: Add flag to do operations only involving AUR.

### ISSUE THREAD

**Issue by kingy9000** [Jguer/yay#74]
Request adding a flag that would make yay only interact with packages installed specifically from the AUR.

This flag could be called `--aur`

While `yay -Su` upgrades all packages, `yay -Su --aur` would only upgrade packages from AUR.

The following AUR helpers already have this implemented:
> [pacaur](https://github.com/rmarquis/pacaur)
> [trizen](https://github.com/trizen/trizen) 

Thank you for reading.

**Comment by Morganamilo** [comment]
Since #97 after `yay -Suy` you could just enter `x-y` to block out non AUR updates. I feel like a `--aur` option would be a bad idea because of dependencies we can't just ignore the main repos.

For example what happens if we do `yay -Suy --aur` and one of the updated aur packages requires a new dependency from the aur. Or if we install a totally new package `yay -S foo --aur` do we pull in it's repo dependencies.

We could make it so `--aur` only applies to the direct targets we ask for and upgrades but dependency checking is still using the normal repos aswell. It feels a little misleading to me if we did that.

**Comment by samosaara** [comment]
It doesn't seems misleading at all to me, it does seems feature creep tough, I can't see an use for it, you do can exclude easily with number range, no point in selecting a package specifically from the AUR since the AUR doesn't have packages with the same names from the default official packages (but this do can become a problem with custom repos), so like what for?

**Comment by Morganamilo** [comment]
To add, some feature I really should document somewhere. The number menu also supports repo names now. So during `-Syu` just like how you can enter `1` to exclude 1 and enter `^1` to only install 1. You can enter `aur` to exclude the AUR and `^aur` to include only AUR packages.
