### ISSUE TITLE
Rebuild package if shared library version changed

### ISSUE THREAD

**Issue by dreuter** [Jguer/yay#743]
Hi :)

Thanks for this awesome aur helper, it is my default ever since I stumbled over it.

#### Affected Version
yay v8.1139 - libalpm v11.0.1

#### Issue
It would be nice if yay could detect, that a package depends on a shared library which changed its version (which means that the old version it was linked against is removed from the filesystem). This leads to a lot of linking/runtime errors, e.g. in [ROS](http://ros.org).

There is already a [python script](https://seangreenslade.com/h/snippets/ros-find-outofdate.py), that is able to detect the packages that need to be rebuild.

This could be integrated into the normal upgrade (e.g. `yay -Syu` or just `yay`).

Maybe this is too heavy on performance and should be a seperate flag.

Any thoughts?

**Comment by Morganamilo** [comment]
That's not a very easy thing to do and is probably out of score.

It would not be hard to use a script with yay to accomplish this though.

```sh
#foo is a script that lists all files that have a linking error
foo | pacman -Qqo - | yay -S - --rebuild
```

The script you gave is similar but only ros specific, and already feeds the packages to pacman -Qo (it could use -q to quiet the output instead of parsing it but that's besides the point). So for that script this would probably do.

```bash
#script tries to be 'friendly' and prints some stuff before the actual package list
#so use tail to cut it out
pyfoo | tail -n+2 | yay -S - rebuild
```

There's also the `--rebuildtree` flag that will achieve what you want, just very inefficiently, especially for ros.

**Comment by Morganamilo** [comment]
>Maybe it could be worth providing such a script with yay (or in a separate AUR package)?

Surely there must be a script already out there somewhere? A script could probably be made using `find` and parsing `ldd`.

**Comment by dreuter** [comment]
I thought it might makes sense to use `pacman -Ql` for that.

Anna <notifications@github.com> schrieb am Do., 4. Okt. 2018 um 10:18 Uhr:

**Comment by Morganamilo** [comment]
Could do, just depends on if you want a generic tool or something pacman specific.

**Comment by Morganamilo** [comment]
I'm going to close this as won't implement, but If you do make something I'd like to see it.
