### ISSUE TITLE
Improved upgrade screen

### ISSUE THREAD

**Issue by wooque** [Jguer/yay#777]
I really like yaourt output on upgrade (`yaourt -Syu[a]`).
Package upgrades are separated from software upgrades.
Software list is sorted by repo (core/extra/community/aur) and then alphabetically.
You can choose packages manually and that will open you list in editor, where you can comment out packages you want to skip

![2018-10-16-133529_394x190_scrot](https://user-images.githubusercontent.com/1936195/47013716-707eaa80-d148-11e8-9ee4-0d26df5aaf0f.png)

![2018-10-16-133540_550x316_scrot](https://user-images.githubusercontent.com/1936195/47013720-73799b00-d148-11e8-822e-ee352deef584.png)

Consider doing something similar in yay

**Comment by Jguer** [comment]
I guess you do not use `yay -Syu --combinedupgrade`? 
Either way, we've decided that type of display is as far as we'll go for reasons that have been discussed in many duplicate issues. 
Of course we'll always consider aesthetic pull requests but this is just not a priority right now to spend development time on since the biggest missing feature there is `open you list in editor,where you can comment out packages you want to skip` which doesn't add anything new

**Comment by Morganamilo** [comment]
>Package upgrades are separated from software upgrades.

I've never seen a point to this. Partial updates are not supported and most people don't use deltas. So really there is no effective difference between the two.
