### ISSUE TITLE
[Request] Show short package description on upgrade menu

### ISSUE THREAD

**Issue by TobiasSekan** [Jguer/yay#827]
Hello,

it would be nice, wehen we can see a short description of a package on the upgrade menu after the version numbers compare. So the no professional Linux users can short see how is how on the upgrade view.

Current view
```
:: 4 Packages to upgrade.
4 core/perl        5.28.0.-1 -> 5.28.1-1
3 core/sqlite      3.25.3-1  -> 3.26.0-1
2 extra/lm_sensors 3.4.0-1   -> 3.5.0.-1
1 extra/mesa       18.2.5-1  -> 18.2.5-2
===>
```

Requested view
```
:: 4 Packages to upgrade.
4 core/perl        5.28.0.-1 -> 5.28.1-1 - A highly capable, feature-rich programming language
3 core/sqlite      3.25.3-1  -> 3.26.0-1 - A C library taht implements an SQL databse engine
2 extra/lm_sensors 3.4.0-1   -> 3.5.0.-1 - Colection of usrr space tools for general SMBus ...
1 extra/mesa       18.2.5-1  -> 18.2.5-2 - An open-source implmentation of the OpenGL ...
===>
```

A setable description length would be nice too.

**Comment by Morganamilo** [comment]
I can't really see a use case for this. When you're installing packages this is useful (hence `yay foo`). But when you're upgrading already installed packages then you should know what the packages are already.

You can manually generate the list with something like `yay -Quq | xargs expac "%-25n: %d"`.

**Comment by TobiasSekan** [comment]
The Intention was, help the none professional Linux user,  they don't know all of the packages (typical 200+)

Alternative:
1. Start System update
2. Abort update
2. Look for one package
3. Start System update
4. Update one Package
5. Goto 1

You really know all of your packages on your system(s) ?

**Comment by Jguer** [comment]
Horizontal real-estate in terminal applications is at a premium. That amount of text will surely create a nightmare on smaller screens using window managers. This is my technical reason for rejecting it, it could be an option but it goes against the lightweight philosophy that we try to uphold.

On a personal note, as a user, this would be like executing `ls` and getting the first 20 lines of each file next to the file name, it seems like a fun idea but it gets tiring fast. Also your last question comes off as attitude which is saddening since @Morganamilo even went to the trouble of putting in prose such a beautiful piece of shell code.
