### ISSUE TITLE
Feature request: add a downgrade option to -S that can check yay's cache

### ISSUE THREAD

**Issue by gwemmie** [Jguer/yay#837]
I'm trying to make an old functionality I had with yaourt work (fully discussed in #477) and it's just ending in frustration no matter what I do. The frustration is I *also* want to be able to have AUR packages in the cache be checked for before rebuilding them, a feature I had taken to creating myself with a script until I switched to yay, which does a better job. That old yaourt functionality was storing AUR packages in `/var/cache/pacman/pkg`, and at this point, frankly, the only reason I still care about this at all anymore is the infamous `downgrade`.

I don't want to stop using `downgrade`, but it's only equipped to deal with a pacman cache, not a yay cache. If yay could downgrade my packages including AUR ones with similar functionality--problem solved, really. Everything else in my system can be rearranged around that and I can stop trying to make AUR packages live in `/var/cache/pacman/pkg/`.

_Before anyone brings up the dangers of a split upgrade, first of all, I know what I'm doing, and I'm in favor of any amount of red tape and warnings around the use of this feature in yay. But second, sometimes a split upgrade by downgrading certain packages is an unfortunate requirement of not taking forever to figure out what exactly went wrong when your system breaks after an upgrade. And yes, that is pretty much the only time I use `downgrade`._

**Comment by AladW** [comment]
![Image of VW](http://www.ogilvy.co.za/wp-content/uploads/2012/10/kettle.jpg)

**Comment by AladW** [comment]
You don't need these kinds of tricks if you use a local repository checked in with git (annex); then when you want an older revision of some package, you just set the whole repo to an older revision, and pacman -S it. No partial upgrades, no `downgrade` and no hacks in the AUR helper needed.

**Comment by Morganamilo** [comment]
I'm in agreement with Alad with the first *point* I already think yay has too many features beyond building AUR packages.

**Comment by Jimi-James** [comment]
I was about to ask about how to do that with yay's cache so that I could also replace `downgrade` with AUR packages, but I just tested and found that `downgrade` itself in fact does not support AUR packages. Rendering the only obstacle I had for abandoning that old yaourt functionality--my entire reason behind my feature request--moot. I guess I just haven't needed to downgrade AUR packages, which says enough on its own. Or at least, not often enough to have needed something easier than simply changing the version number on the PKGBUILD before running makepkg again.
