### ISSUE TITLE
Implement --devel using pkgver() function

### ISSUE THREAD

**Issue by frealgagu** [Jguer/yay#851]
Currently yay is using the git hash to know if a devel package is in its last version. But this approach has a failure if either --gendb is called or .cache/yay/vcs.json is deleted (or migrating from another helper). Is there any way to invoke the pkgver() function to know the current version of packages and update them as necessary?

It has the advantage to work not just for git packages but for any devel package (devel package is considered if pkgver() function is called.

Maybe a different configuration or flag to let use the pkgver instead.

**Comment by Morganamilo** [comment]
There's already an example of how to do it the more traditional way in the man page.

**Comment by frealgagu** [comment]
Thanks, I've not tried yet.
Does the --needed flag query pkgver() and updated the package just in case of changes?

**Comment by Morganamilo** [comment]
the pkgver is always queried when you `-S` something. The `--needed` flag tells yay not to continue with the build and install if the pkgver matches the already installed version.

**Comment by frealgagu** [comment]
Excellent, thanks for the clarification. 

Have you considered to include it into man page or readme? It could be a good idea to execute that command at least once when you are migrating from another helper (or you weren't using any helper at all). --gendb obtains the last found hashes but they could not correspond with the installed packages if they haven't been upgraded before use --gendb

Thank you for this excellent AURHelper.

**Comment by Morganamilo** [comment]
>Have you considered to include it into man page or readme?

`--needed` is an already existing pacman flag, so what it does should already be understood.

>--gendb obtains the last found hashes but they could not correspond with the installed packages if they haven't been upgraded before use --gendb

I don't consider this important because -git packages are always updating. Even if the initial --gendb does not give you a totally up to date system, you'll be fine after the next next update.

That's why personally I'd recommend, running the initial `--gendb` and let eventual correctness take over.

It may be worth mentioning the command in the faq though. Feel free to make a PR.
