### ISSUE TITLE
Error in man page: completioninterval

### ISSUE THREAD

**Issue by simonbcn** [Jguer/yay#859]
```
yay v9.0.1 - libalpm v11.0.2
```

#### Issue
In man page speaks about `completioninterval` configuration setting and in config file shows `completionrefreshtime`.

**Comment by Morganamilo** [comment]
It used to be that and got renamed. Seems the json value was forgotten. Kinda annoying but again the config file is opaque so it should be a non issue.

I'm tempted to change it just because the inconsistency is annoying. But that would be a breaking change for the people who have set custom values. (even if the number of people who have is extremely low)

**Comment by zlatin** [comment]
Why not to change the man? In my opinion it won't break anything but will prevent frustration of those who read man pages.

**Comment by Jguer** [comment]
> I'm tempted to change it just because the inconsistency is annoying. But that would be a breaking change for the people who have set custom values. (even if the number of people who have is extremely low)

I think it's ok to break it for consistency, at worst just the AUR servers will have a break from people who change it to lower values.
