### ISSUE TITLE
Feature Request: Automatic package rebuild when updating its make depedencies

### ISSUE THREAD

**Issue by glebr** [Jguer/yay#971]
There is a problem inherent in AUR: when some make dependencies of package are updated (libs for example) it can stop working until user manually rebuild it. It will be very convenient, if yay will rebuild such package automatically during, for example, running 'yay -Syu'. This feature can resolve many problems, including security, as there are a lot of important packages in AUR (such as custom kernels) which can be built with vulnerable versions of libraries. I think, such feature can be implemented as an option, which is turned on and off in the yay configuration file.

**Comment by Morganamilo** [comment]
See `--rebuildtree`.

**Comment by glebr** [comment]
> See `--rebuildtree`.

Does this not apply only when installing AUR packages? For example, if I will install some lib from AUR by using 'yay -S *library* --rebuildtree', AUR packages, depending on it, will be rebuilt. What if this library is not on the AUR? I checked my packages from AUR and found one of them, which requires rebuilding (clementine-qt5-git because of mesa update), tried to run 'yay -Syu --rebuildtree' and it didn't update clementine.

**Comment by Morganamilo** [comment]
>using 'yay -S library --rebuildtree', AUR packages, depending on it, will be rebuilt.

This is the reverse of what you asked originally.

**Comment by glebr** [comment]
> > using 'yay -S library --rebuildtree', AUR packages, depending on it, will be rebuilt.
> 
> This is the reverse of what you asked originally.

Well, yes, this is an example. In the last sentence I showed that this option is not suitable for automatic package rebuilding that need it when updating. If I'm wrong, correct me, please.

**Comment by Morganamilo** [comment]
Actually reading the title again I think maybe you said the same thing both times. Just the language is fiddly lol.

So yeah, yay supports the opposite of what you want. `--rebuildtree` was easy to implement because it's just the normal dep resolver but it just doesn't stop when encountering a package that's installed.

What you wan't may not be so easy and I have no interest in figuring it all out. If any one wants to implement it then maybe the code for `-Yc` can be reused.

Or maybe you can just pipe a script into yay.

**Comment by AchmadFathoni** [comment]
https://github.com/Skycoder42/repkg
